// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/fim.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FimWatcherConditionType int32

const (
	FimWatcherConditionType_UNKOWN          FimWatcherConditionType = 0
	FimWatcherConditionType_SUBJECT_FAILURE FimWatcherConditionType = 1
)

var FimWatcherConditionType_name = map[int32]string{
	0: "UNKOWN",
	1: "SUBJECT_FAILURE",
}
var FimWatcherConditionType_value = map[string]int32{
	"UNKOWN":          0,
	"SUBJECT_FAILURE": 1,
}

func (x FimWatcherConditionType) String() string {
	return proto.EnumName(FimWatcherConditionType_name, int32(x))
}
func (FimWatcherConditionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fim_99eac21cdc6f4f7c, []int{0}
}

// should be from corev1.ConditionStatus?
type ConditionStatus int32

const (
	ConditionStatus_UNKNOWN ConditionStatus = 0
	ConditionStatus_TRUE    ConditionStatus = 1
	ConditionStatus_FALSE   ConditionStatus = 2
)

var ConditionStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "TRUE",
	2: "FALSE",
}
var ConditionStatus_value = map[string]int32{
	"UNKNOWN": 0,
	"TRUE":    1,
	"FALSE":   2,
}

func (x ConditionStatus) String() string {
	return proto.EnumName(ConditionStatus_name, int32(x))
}
func (ConditionStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fim_99eac21cdc6f4f7c, []int{1}
}

type FimWatcherCondition struct {
	Type   FimWatcherConditionType `protobuf:"varint,1,opt,name=type,proto3,enum=api.FimWatcherConditionType" json:"type,omitempty"`
	Status ConditionStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=api.ConditionStatus" json:"status,omitempty"`
	// Time lastTransitionTime = 3;
	LastTransitionTime   int64    `protobuf:"varint,3,opt,name=lastTransitionTime,proto3" json:"lastTransitionTime,omitempty"`
	Reason               string   `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	Message              string   `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FimWatcherCondition) Reset()         { *m = FimWatcherCondition{} }
func (m *FimWatcherCondition) String() string { return proto.CompactTextString(m) }
func (*FimWatcherCondition) ProtoMessage()    {}
func (*FimWatcherCondition) Descriptor() ([]byte, []int) {
	return fileDescriptor_fim_99eac21cdc6f4f7c, []int{0}
}
func (m *FimWatcherCondition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FimWatcherCondition.Unmarshal(m, b)
}
func (m *FimWatcherCondition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FimWatcherCondition.Marshal(b, m, deterministic)
}
func (dst *FimWatcherCondition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FimWatcherCondition.Merge(dst, src)
}
func (m *FimWatcherCondition) XXX_Size() int {
	return xxx_messageInfo_FimWatcherCondition.Size(m)
}
func (m *FimWatcherCondition) XXX_DiscardUnknown() {
	xxx_messageInfo_FimWatcherCondition.DiscardUnknown(m)
}

var xxx_messageInfo_FimWatcherCondition proto.InternalMessageInfo

func (m *FimWatcherCondition) GetType() FimWatcherConditionType {
	if m != nil {
		return m.Type
	}
	return FimWatcherConditionType_UNKOWN
}

func (m *FimWatcherCondition) GetStatus() ConditionStatus {
	if m != nil {
		return m.Status
	}
	return ConditionStatus_UNKNOWN
}

func (m *FimWatcherCondition) GetLastTransitionTime() int64 {
	if m != nil {
		return m.LastTransitionTime
	}
	return 0
}

func (m *FimWatcherCondition) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *FimWatcherCondition) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type FimWatcherStatus struct {
	ObservablePods       string                 `protobuf:"bytes,1,opt,name=ObservablePods,proto3" json:"ObservablePods,omitempty"`
	Conditions           []*FimWatcherCondition `protobuf:"bytes,2,rep,name=conditions,proto3" json:"conditions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *FimWatcherStatus) Reset()         { *m = FimWatcherStatus{} }
func (m *FimWatcherStatus) String() string { return proto.CompactTextString(m) }
func (*FimWatcherStatus) ProtoMessage()    {}
func (*FimWatcherStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_fim_99eac21cdc6f4f7c, []int{1}
}
func (m *FimWatcherStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FimWatcherStatus.Unmarshal(m, b)
}
func (m *FimWatcherStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FimWatcherStatus.Marshal(b, m, deterministic)
}
func (dst *FimWatcherStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FimWatcherStatus.Merge(dst, src)
}
func (m *FimWatcherStatus) XXX_Size() int {
	return xxx_messageInfo_FimWatcherStatus.Size(m)
}
func (m *FimWatcherStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_FimWatcherStatus.DiscardUnknown(m)
}

var xxx_messageInfo_FimWatcherStatus proto.InternalMessageInfo

func (m *FimWatcherStatus) GetObservablePods() string {
	if m != nil {
		return m.ObservablePods
	}
	return ""
}

func (m *FimWatcherStatus) GetConditions() []*FimWatcherCondition {
	if m != nil {
		return m.Conditions
	}
	return nil
}

type FimWatcherSpec struct {
	// LabelSelector selector = 1;
	Selector             string               `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"`
	Subjects             []*FimWatcherSubject `protobuf:"bytes,2,rep,name=subjects,proto3" json:"subjects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FimWatcherSpec) Reset()         { *m = FimWatcherSpec{} }
func (m *FimWatcherSpec) String() string { return proto.CompactTextString(m) }
func (*FimWatcherSpec) ProtoMessage()    {}
func (*FimWatcherSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_fim_99eac21cdc6f4f7c, []int{2}
}
func (m *FimWatcherSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FimWatcherSpec.Unmarshal(m, b)
}
func (m *FimWatcherSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FimWatcherSpec.Marshal(b, m, deterministic)
}
func (dst *FimWatcherSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FimWatcherSpec.Merge(dst, src)
}
func (m *FimWatcherSpec) XXX_Size() int {
	return xxx_messageInfo_FimWatcherSpec.Size(m)
}
func (m *FimWatcherSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_FimWatcherSpec.DiscardUnknown(m)
}

var xxx_messageInfo_FimWatcherSpec proto.InternalMessageInfo

func (m *FimWatcherSpec) GetSelector() string {
	if m != nil {
		return m.Selector
	}
	return ""
}

func (m *FimWatcherSpec) GetSubjects() []*FimWatcherSubject {
	if m != nil {
		return m.Subjects
	}
	return nil
}

type FimWatcherSubject struct {
	Paths                []string `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	Events               []string `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FimWatcherSubject) Reset()         { *m = FimWatcherSubject{} }
func (m *FimWatcherSubject) String() string { return proto.CompactTextString(m) }
func (*FimWatcherSubject) ProtoMessage()    {}
func (*FimWatcherSubject) Descriptor() ([]byte, []int) {
	return fileDescriptor_fim_99eac21cdc6f4f7c, []int{3}
}
func (m *FimWatcherSubject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FimWatcherSubject.Unmarshal(m, b)
}
func (m *FimWatcherSubject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FimWatcherSubject.Marshal(b, m, deterministic)
}
func (dst *FimWatcherSubject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FimWatcherSubject.Merge(dst, src)
}
func (m *FimWatcherSubject) XXX_Size() int {
	return xxx_messageInfo_FimWatcherSubject.Size(m)
}
func (m *FimWatcherSubject) XXX_DiscardUnknown() {
	xxx_messageInfo_FimWatcherSubject.DiscardUnknown(m)
}

var xxx_messageInfo_FimWatcherSubject proto.InternalMessageInfo

func (m *FimWatcherSubject) GetPaths() []string {
	if m != nil {
		return m.Paths
	}
	return nil
}

func (m *FimWatcherSubject) GetEvents() []string {
	if m != nil {
		return m.Events
	}
	return nil
}

type FimWatcher struct {
	Spec                 *FimWatcherSpec   `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	Status               *FimWatcherStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *FimWatcher) Reset()         { *m = FimWatcher{} }
func (m *FimWatcher) String() string { return proto.CompactTextString(m) }
func (*FimWatcher) ProtoMessage()    {}
func (*FimWatcher) Descriptor() ([]byte, []int) {
	return fileDescriptor_fim_99eac21cdc6f4f7c, []int{4}
}
func (m *FimWatcher) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FimWatcher.Unmarshal(m, b)
}
func (m *FimWatcher) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FimWatcher.Marshal(b, m, deterministic)
}
func (dst *FimWatcher) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FimWatcher.Merge(dst, src)
}
func (m *FimWatcher) XXX_Size() int {
	return xxx_messageInfo_FimWatcher.Size(m)
}
func (m *FimWatcher) XXX_DiscardUnknown() {
	xxx_messageInfo_FimWatcher.DiscardUnknown(m)
}

var xxx_messageInfo_FimWatcher proto.InternalMessageInfo

func (m *FimWatcher) GetSpec() *FimWatcherSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *FimWatcher) GetStatus() *FimWatcherStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type FimWatcherList struct {
	Items                []*FimWatcher `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *FimWatcherList) Reset()         { *m = FimWatcherList{} }
func (m *FimWatcherList) String() string { return proto.CompactTextString(m) }
func (*FimWatcherList) ProtoMessage()    {}
func (*FimWatcherList) Descriptor() ([]byte, []int) {
	return fileDescriptor_fim_99eac21cdc6f4f7c, []int{5}
}
func (m *FimWatcherList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FimWatcherList.Unmarshal(m, b)
}
func (m *FimWatcherList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FimWatcherList.Marshal(b, m, deterministic)
}
func (dst *FimWatcherList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FimWatcherList.Merge(dst, src)
}
func (m *FimWatcherList) XXX_Size() int {
	return xxx_messageInfo_FimWatcherList.Size(m)
}
func (m *FimWatcherList) XXX_DiscardUnknown() {
	xxx_messageInfo_FimWatcherList.DiscardUnknown(m)
}

var xxx_messageInfo_FimWatcherList proto.InternalMessageInfo

func (m *FimWatcherList) GetItems() []*FimWatcher {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*FimWatcherCondition)(nil), "api.FimWatcherCondition")
	proto.RegisterType((*FimWatcherStatus)(nil), "api.FimWatcherStatus")
	proto.RegisterType((*FimWatcherSpec)(nil), "api.FimWatcherSpec")
	proto.RegisterType((*FimWatcherSubject)(nil), "api.FimWatcherSubject")
	proto.RegisterType((*FimWatcher)(nil), "api.FimWatcher")
	proto.RegisterType((*FimWatcherList)(nil), "api.FimWatcherList")
	proto.RegisterEnum("api.FimWatcherConditionType", FimWatcherConditionType_name, FimWatcherConditionType_value)
	proto.RegisterEnum("api.ConditionStatus", ConditionStatus_name, ConditionStatus_value)
}

func init() { proto.RegisterFile("api/fim.proto", fileDescriptor_fim_99eac21cdc6f4f7c) }

var fileDescriptor_fim_99eac21cdc6f4f7c = []byte{
	// 435 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0xc5, 0x75, 0x92, 0xc6, 0x63, 0x91, 0x98, 0x49, 0x29, 0x16, 0xe2, 0x10, 0x59, 0x02, 0xac,
	0x0a, 0x02, 0x72, 0x0f, 0x20, 0x6e, 0xa1, 0x4a, 0x24, 0x68, 0x94, 0xa2, 0x4d, 0xac, 0x1e, 0x61,
	0xe3, 0x0c, 0x74, 0x51, 0x6c, 0xaf, 0xbc, 0xdb, 0x4a, 0xfd, 0x52, 0x7e, 0x07, 0x65, 0xed, 0xa4,
	0xa9, 0xdb, 0x1c, 0x9f, 0xdf, 0x9b, 0x79, 0x6f, 0x66, 0xc7, 0xf0, 0x94, 0x4b, 0xf1, 0xe1, 0xb7,
	0x48, 0x07, 0xb2, 0xc8, 0x75, 0x8e, 0x36, 0x97, 0x22, 0xf8, 0x67, 0x41, 0x6f, 0x2c, 0xd2, 0x4b,
	0xae, 0x93, 0x2b, 0x2a, 0xce, 0xf2, 0x6c, 0x29, 0xb4, 0xc8, 0x33, 0xfc, 0x08, 0x0d, 0x7d, 0x2b,
	0xc9, 0xb7, 0xfa, 0x56, 0xd8, 0x89, 0x5e, 0x0d, 0xb8, 0x14, 0x83, 0x47, 0x74, 0xf3, 0x5b, 0x49,
	0xcc, 0x28, 0xf1, 0x1d, 0xb4, 0x94, 0xe6, 0xfa, 0x5a, 0xf9, 0x07, 0xa6, 0xe6, 0xc8, 0xd4, 0x6c,
	0x95, 0x33, 0xc3, 0xb1, 0x4a, 0x83, 0x03, 0xc0, 0x15, 0x57, 0x7a, 0x5e, 0xf0, 0x4c, 0x95, 0x9d,
	0x44, 0x4a, 0xbe, 0xdd, 0xb7, 0x42, 0x9b, 0x3d, 0xc2, 0xe0, 0x31, 0xb4, 0x0a, 0xe2, 0x2a, 0xcf,
	0xfc, 0x46, 0xdf, 0x0a, 0x1d, 0x56, 0x21, 0xf4, 0xe1, 0x30, 0x25, 0xa5, 0xf8, 0x1f, 0xf2, 0x9b,
	0x86, 0xd8, 0xc0, 0x40, 0x83, 0x77, 0x17, 0xb8, 0x74, 0xc7, 0x37, 0xd0, 0xb9, 0x58, 0x28, 0x2a,
	0x6e, 0xf8, 0x62, 0x45, 0x3f, 0xf2, 0xa5, 0x32, 0xf3, 0x39, 0xac, 0xf6, 0x15, 0x3f, 0x03, 0x24,
	0x9b, 0xe0, 0xeb, 0x79, 0xec, 0xd0, 0x8d, 0xfc, 0x7d, 0x3b, 0x60, 0x3b, 0xda, 0xe0, 0x17, 0x74,
	0x76, 0x5c, 0x25, 0x25, 0xf8, 0x12, 0xda, 0x8a, 0x56, 0x94, 0xe8, 0xbc, 0xa8, 0xdc, 0xb6, 0x18,
	0x23, 0x68, 0xab, 0xeb, 0xc5, 0x5f, 0x4a, 0xf4, 0xc6, 0xe5, 0xb8, 0xe6, 0x32, 0x2b, 0x69, 0xb6,
	0xd5, 0x05, 0x43, 0x78, 0xf6, 0x80, 0xc6, 0x23, 0x68, 0x4a, 0xae, 0xaf, 0xd6, 0xf3, 0xd8, 0xa1,
	0xc3, 0x4a, 0xb0, 0x5e, 0x1a, 0xdd, 0x50, 0x56, 0x35, 0x77, 0x58, 0x85, 0x82, 0x25, 0xc0, 0x5d,
	0x0b, 0x7c, 0x0b, 0x0d, 0x25, 0x29, 0x31, 0xe1, 0xdc, 0xa8, 0x57, 0x0f, 0x20, 0x29, 0x61, 0x46,
	0x80, 0xef, 0xef, 0xbd, 0xb0, 0x1b, 0x3d, 0xaf, 0x4b, 0xef, 0x3d, 0x71, 0xf0, 0x69, 0x77, 0x15,
	0x13, 0xa1, 0x34, 0xbe, 0x86, 0xa6, 0xd0, 0x94, 0x96, 0x29, 0xdd, 0xa8, 0x5b, 0xab, 0x67, 0x25,
	0x7b, 0xf2, 0x05, 0x5e, 0xec, 0x39, 0x35, 0x04, 0x68, 0xc5, 0xd3, 0xf3, 0x8b, 0xcb, 0xa9, 0xf7,
	0x04, 0x7b, 0xd0, 0x9d, 0xc5, 0x5f, 0xbf, 0x8f, 0xce, 0xe6, 0x3f, 0xc7, 0xc3, 0x6f, 0x93, 0x98,
	0x8d, 0x3c, 0xeb, 0xe4, 0x14, 0xba, 0xb5, 0x93, 0x43, 0x17, 0x0e, 0xe3, 0xe9, 0xf9, 0xb4, 0x2c,
	0x6a, 0x43, 0x63, 0xce, 0xe2, 0x91, 0x67, 0xa1, 0x03, 0xcd, 0xf1, 0x70, 0x32, 0x1b, 0x79, 0x07,
	0x8b, 0x96, 0xf9, 0x21, 0x4e, 0xff, 0x07, 0x00, 0x00, 0xff, 0xff, 0xcc, 0x5f, 0xdb, 0x0c, 0x21,
	0x03, 0x00, 0x00,
}
